---
services: docker

language: python
python: "2.7"

env:
  - distro: centos7
  - distro: ubuntu1604

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
- ${PWD}/tests/test.sh
