---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: install.yml
  when: ansible_os_family == "Debian"
  tags:
    - tomcat8
    - tomcat8-install

- include: config.yml
  when: ansible_os_family == "Debian"
  tags:
    - tomcat8
    - tomcat8-config

- include: system-preparation.yml
  when: ansible_os_family == "RedHat"
  tags: tomcat8

- include: asset-preparation.yml
  when: ansible_os_family == "RedHat"
  tags: tomcat8

- include:  service-configuration.yml
  when: ansible_os_family == "RedHat"
  tags: tomcat8

- include:  server-configuration.yml
  when: ansible_os_family == "RedHat"
  tags: tomcat8
