---

- name: tomcat8 | group add
  group: name={{ tomcat_os_group_name }}
  sudo: True


- name: tomcat8 | user add
  user: name={{ tomcat_os_user_name }} group={{ tomcat_os_group_name }} home={{ tomcat_home_path }} createhome=no
  sudo: True
